POST http://localhost:7000/user
Content-Type: application/json; charset=UTF-8

{
  "username": "eric",
  "age": 1
}

### 查询数据库

GET http://localhost:7000/department

### 删除
DELETE http://localhost:7000/department
Content-Type: application/json; charset=UTF-8

{
  "id": 12
}

### 修改
PUT http://localhost:7000/department
Content-Type: application/json; charset=UTF-8

{
  "id": 1,
  "name": "Java1",
  "location": "Shanghai"
}

### 新增
POST http://localhost:7000/department
Content-Type: application/json; charset=UTF-8

{
  "name": "Java7",
  "location": "Shanghai"
}